# when we push on master branch they apply changes on the real web
on:
  push:
    branches:
    - master
    
# to deploy changes on surge host


jobs:
  build:
    name: Deploy React on Surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Prepare yarn on Ubuntu
        run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/yarn.gpg

      - name: Install Yarn
        run: sudo apt update && sudo apt install yarn
        
      - name: Generate Build
        run: yarn build

      - name: Install Surge
        run: npm install --global surge
        
      - name: Deploy Surge
        run: surge ./build/ https://react-base-counter.surge.sh/ ${{ secrets.SURGE_TOKEN }}
